### ISSUE TITLE
Can someone invent their own language pack with this?

### ISSUE THREAD

**Issue by gordonfpanam** [KSP-Localization/SwitchLanguage#1]
If I read this right, I should be able to change settings.cfg to an unused language code and then create my own dictionary for it, without having to recompile the plugin.

**Comment by Olympic1** [comment]
Never tested that, but in theory that should work as long the language code is 2 characters.

Note that the custom language would not be able to use any lingoona stuff as it isn't a supported language.

**Comment by gordonfpanam** [comment]
Thanks for checking.

The example settings.cfg uses 'nl-nl' so I assume five character language codes are supported.

**Comment by Olympic1** [comment]
I think it can be as long as you want it to be, as long it has at least 2 characters. I haven't tested that fully.

**Comment by gordonfpanam** [comment]
This seems to work without fault. Thanks for checking.
